"""ProvenanceValidator — validates the provenance chain for integrity and consistency."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Optional

from research.intelligence.contracts.common import ProvenanceStatus
from research.intelligence.contracts.errors import (
    ResearchError,
    circular_provenance,
    production_promotion_forbidden,
    upstream_commit_missing,
)
from research.intelligence.contracts.claim import ResearchClaim
from research.intelligence.contracts.source_record import ResearchSourceRecord
from research.intelligence.contracts.strategy_seed import StrategySeed


@dataclass
class ProvenanceValidationReport:
    """Report generated by ProvenanceValidator."""

    passed: bool = True
    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    chain_depth: int = 0
    status: ProvenanceStatus = ProvenanceStatus.UNVERIFIED


class ProvenanceValidator:
    """Validates provenance chains across sources, claims, and derived entities."""

    def __init__(
        self,
        source_registry: SourceRegistry,
        claim_registry: ClaimRegistry,
        conflict_registry: ConflictRegistry,
        gap_registry: GapRegistry,
        seed_registry: StrategySeedRegistry,
    ) -> None:
        self._sources = source_registry
        self._claims = claim_registry
        self._conflicts = conflict_registry
        self._gaps = gap_registry
        self._seeds = seed_registry
        self._visited: set[str] = set()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def validate_chain(self, entity_ids: list[str]) -> ProvenanceValidationReport:
        """Run a full provenance check on an ordered chain of entity ids.

        Parameters
        ----------
        entity_ids : list[str]
            Ordered list of entity IDs representing the provenance chain
            (earliest ancestor first, most recent last).

        Returns
        -------
        ProvenanceValidationReport
        """
        self._visited.clear()
        report = ProvenanceValidationReport()

        if not entity_ids:
            report.warnings.append("Provenance chain is empty")
            report.passed = True
            report.status = ProvenanceStatus.UNVERIFIED
            return report

        for i, entity_id in enumerate(entity_ids):
            if not entity_id:
                report.errors.append(str(upstream_commit_missing(f"position {i}")))
                report.passed = False
                continue

            if entity_id in self._visited:
                report.errors.append(str(circular_provenance(entity_id)))
                report.passed = False
                continue

            self._visited.add(entity_id)

        report.chain_depth = len(entity_ids)

        if not report.errors and not report.warnings:
            report.status = ProvenanceStatus.VERIFIED
        elif report.errors:
            report.status = ProvenanceStatus.CONTESTED
        else:
            report.status = ProvenanceStatus.UNVERIFIED_OR_PARTIAL

        return report

    def validate_claims_have_sources(
        self,
        claims: list[ResearchClaim],
        sources: dict[str, ResearchSourceRecord],
    ) -> list[str]:
        """Validate that every claim references at least one known source record.

        Returns a list of error messages (empty = all valid).
        """
        errors: list[str] = []
        for claim in claims:
            has_source = False
            for src_id in claim.source_record_ids:
                if src_id in sources:
                    has_source = True
                    break
            if claim.primary_source_record_id and claim.primary_source_record_id in sources:
                has_source = True
            if not has_source:
                errors.append(
                    f"Claim {claim.claim_id} has no known source_record_id "
                    f"in the provided source registry"
                )
        return errors

    def validate_seeds_have_claims(
        self,
        seeds: list[StrategySeed],
        claims: dict[str, ResearchClaim],
    ) -> list[str]:
        """Validate that every strategy seed references at least one known claim.

        Returns a list of error messages (empty = all valid).
        """
        errors: list[str] = []
        for seed in seeds:
            if not seed.claim_ids:
                errors.append(f"StrategySeed {seed.strategy_seed_id} has no associated claim_ids")
            else:
                missing = [cid for cid in seed.claim_ids if cid not in claims]
                if missing:
                    errors.append(
                        f"StrategySeed {seed.strategy_seed_id} references unknown "
                        f"claim_ids: {missing}"
                    )
        return errors

    def validate_no_circular_dependencies(
        self,
        seeds: list[StrategySeed],
    ) -> list[str]:
        """Detect circular dependencies among strategy seeds via origin_refs.

        Returns a list of error messages (empty = no cycles).
        """
        errors: list[str] = []
        seed_map = {s.strategy_seed_id: s for s in seeds}

        def _detect_cycle(start_id: str, current_id: str, visited: set[str]) -> bool:
            if current_id in visited:
                return True
            visited.add(current_id)
            seed = seed_map.get(current_id)
            if seed:
                for ref in seed.origin_refs:
                    if ref in seed_map:
                        if _detect_cycle(start_id, ref, visited.copy()):
                            return True
            return False

        for seed in seeds:
            visited: set[str] = set()
            if _detect_cycle(seed.strategy_seed_id, seed.strategy_seed_id, visited):
                errors.append(str(circular_provenance(seed.strategy_seed_id)))

        return errors

    def validate_github_commit(
        self,
        source: ResearchSourceRecord,
    ) -> list[str]:
        """Validate that a source record has an upstream commit reference if it
        originates from a GitHub repository.

        Returns a list of error messages (empty = valid).
        """
        errors: list[str] = []
        if "github" in source.repository.lower() and not source.upstream_commit:
            errors.append(str(upstream_commit_missing(source.source_record_id)))
        return errors

    def validate_production_promotion(
        self,
        seed: StrategySeed,
    ) -> list[str]:
        """Validate that a strategy seed is not promoted to production when
        it is not production_eligible.

        Returns a list of error messages (empty = promotion allowed).
        """
        errors: list[str] = []
        if seed.production_eligible and seed.research_status not in (
            "validation_ready",
            "specification_ready",
        ):
            # Production promotion is forbidden for non-validated seeds
            errors.append(str(production_promotion_forbidden(seed.strategy_seed_id)))
        return errors

    def reset(self) -> None:
        """Clear internal visited set (start a fresh validation session)."""
        self._visited.clear()
