import argparse
from datetime import datetime
from pathlib import Path

import pandas as pd


ROOT = Path(__file__).resolve().parents[1]


COMMANDS = [
    {
        "command_id": "quality_gate",
        "category": "project_os",
        "command": "python scripts/run_v06_quality_gate.py",
        "purpose": "Run the full v0.6 gate, refresh Project State, Dashboard, Claude indexes, and Project OS validation.",
        "primary_outputs": "docs/PROJECT_DASHBOARD.md; results/project_os_validation_report.md",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Preferred full refresh command.",
    },
    {
        "command_id": "daily_private_pilot",
        "category": "publishing_draft",
        "command": "python scripts/run_daily_private_pilot.py",
        "purpose": "Run the local private-pilot MVP workflow: prefilter candidates, generate drafts, validate draft safety, summarize feedback, classify other_review reasons, build approved pool, and refresh the dashboard.",
        "primary_outputs": "data/event_candidates_v06_tg_prefilter_pass.csv; data/tg_drafts_v06_private_pilot.csv; data/tg_drafts_v06_approved_pool.csv; results/daily_private_pilot_report.md",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Does not call Telegram, does not auto-send, and does not use market-data network calls.",
    },
    {
        "command_id": "daily_private_pilot_ai_review",
        "category": "publishing_draft",
        "command": "python scripts/run_daily_private_pilot.py --ai-review",
        "purpose": "Run the local private-pilot workflow and fill draft review fields with Claude/OpenRouter suggestions.",
        "primary_outputs": "data/tg_drafts_v06_private_pilot.csv; data/tg_drafts_v06_private_pilot_ai_reviewed.csv; results/tg_draft_ai_review_summary.csv; results/daily_private_pilot_report.md",
        "safe_default": "conditional",
        "requires_network": "yes",
        "requires_secret": "yes",
        "notes": "Requires OPENROUTER_API_KEY only in the current terminal environment. Does not call Telegram or auto-send.",
    },
    {
        "command_id": "daily_private_pilot_report",
        "category": "publishing_draft",
        "command": "python scripts/build_daily_private_pilot_report.py",
        "purpose": "Build the one-page daily private-pilot report from draft, validation, feedback, other_review, dashboard, and Claude backlog state.",
        "primary_outputs": "results/daily_private_pilot_summary.csv; results/daily_private_pilot_report.md",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Read-only report generator.",
    },
    {
        "command_id": "tg_draft_rule_improvement",
        "category": "publishing_draft",
        "command": "python scripts/build_tg_draft_rule_improvement_report.py",
        "purpose": "Convert AI-rejected/noisy TG drafts into concrete local rule-improvement candidates.",
        "primary_outputs": "results/tg_draft_rule_improvement_report.csv; results/tg_draft_rule_improvement_report.md",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Local analysis only; does not change classification rules by itself.",
    },
    {
        "command_id": "project_os_validation",
        "category": "project_os",
        "command": "python scripts/validate_project_os.py",
        "purpose": "Validate Project OS freshness, gates, boundary checks, secret scan state, and Claude decision consistency.",
        "primary_outputs": "results/project_os_validation_report.md; results/project_os_validation_summary.csv",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Use after generating prerequisite reports, or run quality_gate instead.",
    },
    {
        "command_id": "secret_scan",
        "category": "security",
        "command": "python scripts/check_secret_leaks.py",
        "purpose": "Scan local project text files for likely leaked API keys, tokens, passwords, and private keys.",
        "primary_outputs": "results/secret_leak_report.md; results/secret_leak_summary.csv",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Report uses redacted matches only.",
    },
    {
        "command_id": "local_environment",
        "category": "project_os",
        "command": "python scripts/check_local_environment.py",
        "purpose": "Check Python version, required packages, required directories, and optional Claude API key environment state.",
        "primary_outputs": "results/local_environment_report.md; results/local_environment_summary.csv",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "OPENROUTER_API_KEY is informational; missing is acceptable unless querying Claude.",
    },
    {
        "command_id": "cursor_prompt",
        "category": "agent_handoff",
        "command": "python scripts/generate_cursor_prompt.py",
        "purpose": "Generate file-based Cursor handoff prompt from local Project OS state.",
        "primary_outputs": "docs/CURSOR_NEXT_PROMPT.md",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Does not automate Cursor UI.",
    },
    {
        "command_id": "claude_prompt",
        "category": "agent_handoff",
        "command": "python scripts/generate_claude_question_prompt.py --force",
        "purpose": "Generate the current Claude consultation prompt from backlog, state, decisions, and review packets.",
        "primary_outputs": "docs/CLAUDE_NEXT_PROMPT.md",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Does not send the prompt.",
    },
    {
        "command_id": "claude_query",
        "category": "agent_handoff",
        "command": "python scripts/query_claude_next.py",
        "purpose": "Send docs/CLAUDE_NEXT_PROMPT.md to Claude via OpenRouter and refresh Project OS after response.",
        "primary_outputs": "results/claude_next_response_*.md; docs/CLAUDE_RESPONSE_INDEX.md; docs/CLAUDE_DECISION_REVIEW.md",
        "safe_default": "conditional",
        "requires_network": "yes",
        "requires_secret": "yes",
        "notes": "Requires OPENROUTER_API_KEY in the current terminal environment. Do not write the key to files.",
    },
    {
        "command_id": "claude_index",
        "category": "agent_handoff",
        "command": "python scripts/index_claude_responses.py",
        "purpose": "Index local Claude response files stored in results/.",
        "primary_outputs": "docs/CLAUDE_RESPONSE_INDEX.md; results/claude_response_index.csv",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Does not mark recommendations as accepted.",
    },
    {
        "command_id": "claude_decision_review",
        "category": "agent_handoff",
        "command": "python scripts/build_claude_decision_review_queue.py",
        "purpose": "Extract reviewable decision/action items from Claude responses without auto-applying them.",
        "primary_outputs": "docs/CLAUDE_DECISION_REVIEW.md; data/claude_decision_review_queue.csv",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Accepted direction still requires docs/DECISIONS.md entry.",
    },
    {
        "command_id": "project_review_actions",
        "category": "project_os",
        "command": "python scripts/build_project_review_actions.py",
        "purpose": "Turn dashboard review metrics into explicit action items with owner, next step, and evidence.",
        "primary_outputs": "docs/PROJECT_REVIEW_ACTIONS.md; data/project_review_action_queue.csv",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Does not approve direction-level changes.",
    },
    {
        "command_id": "artifact_manifest",
        "category": "project_os",
        "command": "python scripts/build_artifact_manifest.py",
        "purpose": "Build a required artifact manifest so core local files are visible and protected from accidental deletion.",
        "primary_outputs": "docs/ARTIFACT_MANIFEST.md; results/artifact_manifest.csv; results/artifact_manifest_summary.csv",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Checks existence and freshness policy for core project outputs.",
    },
    {
        "command_id": "v07_first_hand_watchers",
        "category": "first_hand_intel",
        "command": "python scripts/run_v07_first_hand_watchers.py --hours 24 --limit-alerts 100",
        "purpose": "Run the local v0.7 first-hand watcher MVP: watched address alerts, stablecoin mint/burn alerts, Hyperliquid large-position alerts, event normalization, and TG draft preview.",
        "primary_outputs": "data/watcher_alerts_raw.csv; data/watcher_alerts_hyperliquid_positions.csv; data/watcher_events_raw.csv; data/tg_drafts_v07_watcher_private_pilot.csv; results/v07_watcher_daily_report.md",
        "safe_default": "yes",
        "requires_network": "conditional",
        "requires_secret": "conditional",
        "notes": "Uses ETHERSCAN_API_KEY from the current terminal if set for Ethereum sources. Hyperliquid uses its public info endpoint. Does not call Telegram or auto-send.",
    },
    {
        "command_id": "v07_watchlist_validation",
        "category": "first_hand_intel",
        "command": "python scripts/validate_v07_watchlists.py",
        "purpose": "Validate v0.7 watcher address, stablecoin, and Hyperliquid watchlists before live API/TG testing.",
        "primary_outputs": "results/v07_watchlist_validation_report.csv; results/v07_watchlist_validation_summary.csv; results/v07_watchlist_validation_report.md",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Checks address format, duplicates, required labels/entities/categories, and positive thresholds.",
    },
    {
        "command_id": "v07_first_hand_watchers_backfill",
        "category": "first_hand_intel",
        "command": "python scripts/run_v07_first_hand_watchers.py --hours 24 --limit-alerts 100 --backfill",
        "purpose": "Run v0.7 watcher MVP and verify normalized watcher events against the existing Binance price backfill/quality pipeline.",
        "primary_outputs": "results/v07_watcher_event_price_backfill.csv; results/v07_watcher_event_quality_report.csv; results/tg_drafts_v07_watcher_validation_summary.csv",
        "safe_default": "conditional",
        "requires_network": "yes",
        "requires_secret": "conditional",
        "notes": "Backfill uses public Binance market data. Live watcher mode requires ETHERSCAN_API_KEY in the current terminal; no Telegram send.",
    },
    {
        "command_id": "tg_draft_test_send_dry_run",
        "category": "publishing_draft",
        "command": "python scripts/send_tg_draft_test.py --input data/tg_drafts_v07_watcher_private_pilot.csv --limit 1",
        "purpose": "Dry-run one local TG draft test message without calling Telegram.",
        "primary_outputs": "results/tg_draft_test_send_summary.csv",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Prints message preview only. No Telegram API call.",
    },
    {
        "command_id": "tg_draft_test_send",
        "category": "publishing_draft",
        "command": "python scripts/send_tg_draft_test.py --input data/tg_drafts_v07_watcher_private_pilot.csv --limit 1 --send",
        "purpose": "Manually send one local TG draft test message after TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID are set in the current terminal.",
        "primary_outputs": "results/tg_draft_test_send_summary.csv",
        "safe_default": "conditional",
        "requires_network": "yes",
        "requires_secret": "yes",
        "notes": "Manual test only. Refuses auto_send_enabled=true rows. Does not store token or chat id.",
    },
    {
        "command_id": "v07_tg_live_monitor",
        "category": "publishing_live",
        "command": "python scripts/run_v07_tg_live_monitor.py --send --interval-seconds 300 --max-send-per-cycle 3 --limit-alerts 100",
        "purpose": "Continuously run first-hand watchers, validate TG drafts, dedupe by candidate_id, and send new watcher alerts to Telegram.",
        "primary_outputs": "results/v07_tg_live_monitor_summary.csv; data/tg_live_sent_state.csv; results/v07_tg_live_monitor.log",
        "safe_default": "conditional",
        "requires_network": "yes",
        "requires_secret": "yes",
        "notes": "Loads ignored local secrets if present. Use scripts/stop_v07_tg_live_monitor.ps1 to stop the background monitor. No trading integration.",
    },
    {
        "command_id": "v07_tg_live_monitor_stop",
        "category": "publishing_live",
        "command": "powershell -ExecutionPolicy Bypass -File scripts/stop_v07_tg_live_monitor.ps1",
        "purpose": "Stop the background v0.7 watcher-to-TG live monitor using the recorded pid file.",
        "primary_outputs": "results/v07_tg_live_monitor.pid",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Does not delete sent-state. Existing dedupe history remains intact.",
    },
    {
        "command_id": "binance_long_short_snapshot",
        "category": "market_structure",
        "command": "python scripts/watch_binance_long_short_ratios.py --output data/binance_long_short_snapshot.csv --summary results/v08_binance_long_short_summary.csv --period 1h --limit 2",
        "purpose": "Fetch public Binance USD-M top-trader/global long-short and taker buy-sell ratios for morning digest context.",
        "primary_outputs": "data/binance_long_short_snapshot.csv; results/v08_binance_long_short_summary.csv",
        "safe_default": "conditional",
        "requires_network": "yes",
        "requires_secret": "no",
        "notes": "Public market-data only. Context for crowding/structure, not a direction instruction.",
    },
    {
        "command_id": "tg_morning_digest",
        "category": "publishing_digest",
        "command": "python scripts/build_tg_morning_digest.py --output results/v08_tg_morning_digest.md --summary results/v08_tg_morning_digest_summary.csv",
        "purpose": "Build the China-time morning digest for the previous evening/night window without sending to Telegram.",
        "primary_outputs": "results/v08_tg_morning_digest.md; results/v08_tg_morning_digest_summary.csv; data/binance_long_short_snapshot.csv",
        "safe_default": "conditional",
        "requires_network": "yes",
        "requires_secret": "no",
        "notes": "Dry-run/report mode. Server timer uses --send with Telegram env loaded at runtime.",
    },
    {
        "command_id": "tg_noon_digest",
        "category": "publishing_digest",
        "command": "python scripts/build_tg_morning_digest.py --digest-label noon --window-end-hour 12 --window-hours 4 --output results/v08_tg_noon_digest.md --summary results/v08_tg_noon_digest_summary.csv",
        "purpose": "Build the China-time noon digest for the morning window without sending to Telegram.",
        "primary_outputs": "results/v08_tg_noon_digest.md; results/v08_tg_noon_digest_summary.csv; data/binance_long_short_snapshot.csv",
        "safe_default": "conditional",
        "requires_network": "yes",
        "requires_secret": "no",
        "notes": "Dry-run/report mode. Server timer uses --send with Telegram env loaded at runtime.",
    },
    {
        "command_id": "tg_evening_digest",
        "category": "publishing_digest",
        "command": "python scripts/build_tg_morning_digest.py --digest-label evening --window-end-hour 20 --window-hours 8 --output results/v08_tg_evening_digest.md --summary results/v08_tg_evening_digest_summary.csv",
        "purpose": "Build the China-time evening digest for the daytime window without sending to Telegram.",
        "primary_outputs": "results/v08_tg_evening_digest.md; results/v08_tg_evening_digest_summary.csv; data/binance_long_short_snapshot.csv",
        "safe_default": "conditional",
        "requires_network": "yes",
        "requires_secret": "no",
        "notes": "Dry-run/report mode. Server timer uses --send with Telegram env loaded at runtime.",
    },
    {
        "command_id": "tg_sent_state_metadata_enrichment",
        "category": "publishing_quality",
        "command": "python scripts/enrich_tg_sent_state_metadata.py",
        "purpose": "Backfill missing event_type/asset/severity metadata in local TG sent-state rows from local TG draft CSV files.",
        "primary_outputs": "data/tg_live_sent_state.csv; results/v08_tg_sent_state_metadata_enrichment_summary.csv",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Creates a .bak backup before overwriting sent-state. Does not send Telegram messages.",
    },
    {
        "command_id": "tg_source_usefulness_report",
        "category": "publishing_quality",
        "command": "python scripts/build_tg_source_usefulness_report.py --lookback-days 7",
        "purpose": "Summarize live TG source usefulness from sent alerts and 4h/24h follow-up coverage.",
        "primary_outputs": "results/v08_tg_source_usefulness_report.md; results/v08_tg_source_usefulness_summary.csv; results/v08_tg_source_usefulness_by_source.csv",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Local quality/operations report only. Uses sent alerts and 4h/24h follow-up data; does not use Telegram replies or reactions. Does not provide trading advice.",
    },
    {
        "command_id": "tg_quality_loop",
        "category": "publishing_quality",
        "command": "python scripts/run_tg_quality_loop.py --lookback-days 7 --followup-min-age-hours 4",
        "purpose": "Run the full TG quality loop: sent-state metadata enrichment, follow-up report, and source usefulness report.",
        "primary_outputs": "results/v08_tg_quality_loop_summary.csv; results/v08_tg_alert_followup_report.md; results/v08_tg_source_usefulness_report.md",
        "safe_default": "yes",
        "requires_network": "yes",
        "requires_secret": "no",
        "notes": "Uses public Binance market data through follow-up backfill. Does not collect Telegram replies/reactions, send messages, or trade.",
    },
    {
        "command_id": "historical_signal_replay_broad_200",
        "category": "backtest",
        "command": "python scripts/run_v08_historical_signal_replay.py --limit 200 --mode broad",
        "purpose": "Replay up to 200 older mature historical candidates through event price backfill to increase signal sample size.",
        "primary_outputs": "data/events_v08_historical_replay_broad_200.csv; results/v08_historical_replay_broad_200_price_backfill.csv; results/v08_historical_replay_broad_200_findings.md",
        "safe_default": "conditional",
        "requires_network": "yes",
        "requires_secret": "no",
        "notes": "Uses public Binance data and local cache. Research/quality analysis only; not a live publishing rule.",
    },
    {
        "command_id": "historical_signal_replay_conservative_120",
        "category": "backtest",
        "command": "python scripts/run_v08_historical_signal_replay.py --limit 120 --mode conservative",
        "purpose": "Replay a cleaner high-score subset of older mature historical candidates for comparison against broad replay.",
        "primary_outputs": "data/events_v08_historical_replay_conservative_120.csv; results/v08_historical_replay_conservative_120_price_backfill.csv; results/v08_historical_replay_conservative_120_findings.md",
        "safe_default": "conditional",
        "requires_network": "yes",
        "requires_secret": "no",
        "notes": "Still dominated by BTC/macro in the current dataset; interpret abnormal-vs-BTC carefully.",
    },
    {
        "command_id": "historical_source_usefulness_v081",
        "category": "source_quality",
        "command": "python scripts/build_historical_source_usefulness_from_backtest.py --backfill results/v08_historical_replay_conservative_120_price_backfill.csv --quality results/v08_historical_replay_conservative_120_quality_report.csv --by-event-type results/v081_historical_source_usefulness_by_event_type.csv --by-source results/v081_historical_source_usefulness_by_source.csv --summary results/v081_historical_source_usefulness_summary.csv --output results/v081_historical_source_usefulness_report.md",
        "purpose": "Summarize event/source usefulness from historical backtest rows after v081 token-unlock cleanup.",
        "primary_outputs": "results/v081_historical_source_usefulness_report.md; results/v081_historical_source_usefulness_by_event_type.csv; results/v081_historical_source_usefulness_by_source.csv",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Research/source QA only. Does not send Telegram messages or produce trade instructions.",
    },
    {
        "command_id": "source_readiness_v081",
        "category": "source_quality",
        "command": "python scripts/build_v08_source_readiness_report.py --candidates data/event_candidates_real_500_older_v081_review_suggested.csv --historical-event-type results/v081_historical_source_usefulness_by_event_type.csv --historical-source results/v081_historical_source_usefulness_by_source.csv --output results/v081_source_readiness_report.md --summary results/v081_source_readiness_summary.csv",
        "purpose": "Build readiness checklist for token unlock, CEX listings, CEX netflow baseline, Hyperliquid state history, and source usefulness.",
        "primary_outputs": "results/v081_source_readiness_report.md; results/v081_source_readiness_summary.csv",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Uses local historical replay outputs and watcher state files. Source QA only.",
    },
    {
        "command_id": "source_quality_reports_v081",
        "category": "source_quality",
        "command": "python scripts/run_v081_source_quality_reports.py",
        "purpose": "Run token unlock calendar quality, CEX netflow baseline, Hyperliquid state history, historical usefulness, and source readiness reports.",
        "primary_outputs": "results/v081_token_unlock_calendar_quality_report.md; results/v081_cex_netflow_baseline_report.md; results/v081_hyperliquid_state_history_report.md; results/v081_source_readiness_report.md",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Local report refresh only. Does not send Telegram messages, call Notion, or trade.",
    },
    {
        "command_id": "source_registry_report_v11",
        "category": "source_quality",
        "command": "python scripts/build_source_registry_report.py --registry data/source_registry.csv --summary results/source_registry_report.csv --output results/source_registry_report.md",
        "purpose": "Validate source registry coverage against watcher events, alert ledger, and decision logs.",
        "primary_outputs": "results/source_registry_report.md; results/source_registry_report.csv",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Source governance report. Does not send Telegram messages or call external APIs.",
    },
    {
        "command_id": "source_effectiveness_report_v11",
        "category": "source_quality",
        "command": "python scripts/build_source_effectiveness_report.py --registry data/source_registry.csv --output results/source_effectiveness_report.csv --markdown-output results/source_effectiveness_report.md --summary results/source_effectiveness_summary.csv",
        "purpose": "Estimate source-level usefulness from sent alert ledger, outcome rows, and routing decisions.",
        "primary_outputs": "results/source_effectiveness_report.md; results/source_effectiveness_report.csv; results/source_effectiveness_summary.csv",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Insufficient samples are reported explicitly. Research/source QA only.",
    },
    {
        "command_id": "event_type_performance_matrix_v11",
        "category": "source_quality",
        "command": "python scripts/build_event_type_performance_matrix.py --outcomes data/tg_alert_outcomes.csv --historical-backfill results/v08_historical_replay_broad_200_price_backfill.csv --historical-quality results/v08_historical_replay_broad_200_quality_report.csv --output results/event_type_performance_matrix.csv --summary results/event_type_performance_matrix_summary.csv --markdown-output results/event_type_performance_matrix.md",
        "purpose": "Build event-type/source-subtype performance matrix across live and historical outcomes.",
        "primary_outputs": "results/event_type_performance_matrix.md; results/event_type_performance_matrix.csv; results/event_type_performance_matrix_summary.csv",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Separates insufficient samples and weak/context-only buckets. No trade instructions.",
    },
    {
        "command_id": "historical_signal_replay_non_benchmark_alt_50",
        "category": "backtest",
        "command": "python scripts/run_v08_historical_signal_replay.py --limit 50 --mode non_benchmark_alt",
        "purpose": "Replay mature historical non-BTC/ETH, non-macro altcoin candidates to reduce benchmark/macro pollution.",
        "primary_outputs": "data/events_v08_historical_replay_non_benchmark_alt_50.csv; results/v08_historical_replay_non_benchmark_alt_50_price_backfill.csv; results/v08_historical_replay_non_benchmark_alt_50_findings.md",
        "safe_default": "conditional",
        "requires_network": "yes",
        "requires_secret": "no",
        "notes": "Uses public Binance data and local cache. Research/source QA only; not a publishing or trade rule.",
    },
    {
        "command_id": "event_type_performance_matrix_non_benchmark_alt_v11",
        "category": "source_quality",
        "command": "python scripts/build_event_type_performance_matrix.py --outcomes data/tg_alert_outcomes.csv --historical-backfill results/v08_historical_replay_non_benchmark_alt_200_price_backfill.csv --historical-quality results/v08_historical_replay_non_benchmark_alt_200_quality_report.csv --output results/event_type_performance_matrix_non_benchmark_alt.csv --summary results/event_type_performance_matrix_non_benchmark_alt_summary.csv --markdown-output results/event_type_performance_matrix_non_benchmark_alt.md",
        "purpose": "Build event performance matrix from the non-benchmark altcoin historical replay sample.",
        "primary_outputs": "results/event_type_performance_matrix_non_benchmark_alt.md; results/event_type_performance_matrix_non_benchmark_alt.csv; results/event_type_performance_matrix_non_benchmark_alt_summary.csv",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Used by v11 signal policy to reduce BTC/macro benchmark pollution.",
    },
    {
        "command_id": "signal_policy_v12_strict",
        "category": "source_quality",
        "command": "python scripts/validate_whale_position_contamination.py && python scripts/validate_hack_classification.py && python scripts/apply_boost_criteria_v12.py",
        "purpose": "Build strict contamination-aware TG routing policy after whale and hack subtype validation.",
        "primary_outputs": "data/tg_signal_policy_v12.csv; results/v12_boost_criteria_report.csv; results/v12_whale_position_contamination_report.md; results/v12_hack_classification_report.csv",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Prevents apparent historical alpha from becoming a boost when HYPE, single-asset, short-window, or hack-subtype contamination is detected.",
    },
    {
        "command_id": "v13_historical_quality_audit",
        "category": "source_quality",
        "command": "python scripts/validate_price_in_effect.py && python scripts/grade_other_quality.py && python scripts/analyze_hype_contamination_detail.py && python scripts/analyze_whale_position_asset_contamination.py && python scripts/build_source_identity_layers.py && python scripts/build_regime_layer_report.py && python scripts/validate_hack_classification.py && python scripts/build_active_exploit_urgent_candidates.py && python scripts/apply_boost_criteria_v12.py",
        "purpose": "Run the Claude-directed v13 historical quality audit: price-in, other grading, HYPE/whale contamination, source identity, regime layer, and active-exploit urgent candidates.",
        "primary_outputs": "results/v13_price_in_report.md; results/v13_other_quality_report.md; results/v13_hype_contamination_report.md; results/v13_whale_asset_contamination_report.md; data/source_identity_layers.csv; results/v13_regime_layer_report.md; results/v13_active_exploit_urgent_candidates.md; data/tg_signal_policy_v12.csv",
        "safe_default": "conditional",
        "requires_network": "yes",
        "requires_secret": "no",
        "notes": "Uses public Binance for price-in/regime checks. Research/source QA only; no trade advice and no TG sending.",
    },
    {
        "command_id": "v13_extended_history_replay_500",
        "category": "backtest",
        "command": "python scripts/run_v08_historical_signal_replay.py --input data/event_candidates_real_5000_older_7_365d_mature_tightened.csv --limit 500 --mode non_benchmark_alt",
        "purpose": "Run extended strict non-benchmark alt historical replay after candidate tightening and HYPE whale exclusion.",
        "primary_outputs": "results/v08_historical_replay_non_benchmark_alt_500_price_backfill.csv; results/v08_historical_replay_non_benchmark_alt_500_quality_report.csv; results/v08_historical_replay_non_benchmark_alt_500_findings.md",
        "safe_default": "conditional",
        "requires_network": "yes",
        "requires_secret": "no",
        "notes": "Uses public Binance data. Current strict eligible count is below 500 when source quality is enforced.",
    },
    {
        "command_id": "v13_post_hype_source_regime_refresh",
        "category": "source_quality",
        "command": "python scripts/archive_hype_and_recompute_stats.py --backfill results/v08_historical_replay_non_benchmark_alt_500_price_backfill.csv --output data/backtest_v13_extended_alt_history_clean.csv --summary results/v13_extended_post_hype_removal_summary.csv --group-stats results/v13_extended_post_hype_removal_group_stats.csv --markdown-output results/v13_extended_post_hype_removal_report.md && python scripts/analyze_whale_position_asset_contamination.py --backfill results/v08_historical_replay_non_benchmark_alt_500_price_backfill.csv --output results/v13_extended_whale_asset_contamination_report.csv --summary results/v13_extended_whale_asset_contamination_summary.csv --markdown-output results/v13_extended_whale_asset_contamination_report.md && python scripts/build_source_identity_layers.py --candidates data/event_candidates_real_5000_older_7_365d_mature_tightened.csv --backfill results/v08_historical_replay_non_benchmark_alt_500_price_backfill.csv --output data/source_identity_layers_v13_extended.csv --summary results/v13_extended_source_identity_summary.csv --markdown-output results/v13_extended_source_identity_layers.md && python scripts/score_and_throttle_sources.py --source-layers data/source_identity_layers_v13_extended.csv --clean-backfill data/backtest_v13_extended_alt_history_clean.csv --output data/source_scores_v13_extended.csv --rules results/v13_extended_source_throttle_rules.csv --markdown-output results/v13_extended_source_throttle_report.md",
        "purpose": "Refresh post-HYPE group stats, whale contamination, source identity, and source throttling from the extended replay.",
        "primary_outputs": "results/v13_extended_post_hype_removal_report.md; results/v13_extended_whale_asset_contamination_report.md; data/source_scores_v13_extended.csv; results/v13_extended_source_throttle_report.md",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "No Telegram sending. Used to keep product routing aligned with historical quality results.",
    },
    {
        "command_id": "v14_time_and_source_audit",
        "category": "source_quality",
        "command": "python scripts/diagnose_remote_time_fields.py && python scripts/split_webhook_subsources.py && python scripts/analyze_needs_taxonomy_review.py",
        "purpose": "Run Claude-directed v14 fixes for remote time-field diagnosis, webhook subsource scoring, and needs_taxonomy_review cleanup.",
        "primary_outputs": "results/v14_time_field_diagnosis.md; data/source_scores_v14_webhook_split.csv; data/taxonomy_review_reclassified.csv",
        "safe_default": "conditional",
        "requires_network": "yes",
        "requires_secret": "conditional",
        "notes": "Time diagnosis may use remote read-only export credentials if configured locally. Does not modify remote data or send Telegram messages.",
    },
    {
        "command_id": "v14_digest_quality_filters",
        "category": "publishing_quality",
        "command": "python scripts/split_flow_event_subtypes.py; python scripts/filter_etf_fund_flow.py; python scripts/verify_exploit_amounts.py; python scripts/build_v14_short_price_in.py --limit 281; python scripts/classify_v14_upgrade_events.py; python scripts/build_v14_prefilter.py; python scripts/build_v14_composer_scores.py; python scripts/apply_v14_publish_policy.py; python scripts/define_publishable_event_criteria.py; python scripts/apply_v14_publish_policy.py; python scripts/build_v14_digest_preview.py",
        "purpose": "Split flow subtypes, apply v14 quality filters, build short price-in checks, classify upgrade events, run hard PreFilter, build gate-based Composer output, evaluate minimum publishable criteria, enforce block/digest/interrupt policy, then build a strict digest preview.",
        "primary_outputs": "data/v14_flow_event_subtypes.csv; data/etf_fund_flow_filtered.csv; data/active_exploit_verified.csv; data/v14_short_price_in.csv; data/v14_upgrade_events.csv; data/v14_prefilter_results.csv; data/v14_composer_scores.csv; data/v14_publishable_criteria_eval.csv; data/v14_publish_policy_candidates.csv; results/v14_digest_preview.md",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Preview only. Does not send Telegram messages and excludes rows failing source, amount, context, or asset-consistency gates.",
    },
    {
        "command_id": "v14_security_alert_ingest",
        "category": "source_ingest",
        "command": "python scripts/ingest_security_alerts.py --source etherscan-labels --label phish-hack --limit 200",
        "purpose": "Try ingesting external security address-risk labels into local normalized CSV.",
        "primary_outputs": "data/security_events/security_events_normalized.csv; results/v14_security_alert_ingest_summary.csv",
        "safe_default": "yes",
        "requires_network": "yes",
        "requires_secret": "yes",
        "notes": "Requires ETHERSCAN_API_KEY in environment. Current Etherscan metadata export may require higher access level; failure is recorded as warning without leaking the key.",
    },
    {
        "command_id": "v14_etf_daily_digest",
        "category": "daily_digest",
        "command": "python scripts/build_etf_daily_digest.py",
        "purpose": "Fetch Farside public BTC ETF flow table and build daily ETF flow digest candidate.",
        "primary_outputs": "data/etf_daily_flows_farside.csv; results/v14_etf_daily_digest.md; results/v14_etf_daily_digest_summary.csv",
        "safe_default": "yes",
        "requires_network": "yes",
        "requires_secret": "no",
        "notes": "Daily ETF flow belongs in evening digest, not intraday alerting. Uses public web data and marks low-flow days as archive-only.",
    },
    {
        "command_id": "v14_first_hand_publish_candidates",
        "category": "publishing_quality",
        "command": "python scripts/build_first_hand_publish_candidates.py",
        "purpose": "Route first-hand watcher alerts into intraday, digest, daily digest, or archive candidates.",
        "primary_outputs": "data/v14_first_hand_publish_candidates.csv; results/v14_first_hand_publish_candidates_summary.csv; results/v14_first_hand_publish_candidates.md",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Static Hyperliquid snapshots are archived unless there is a real state change; token unlocks are digest-only; CEX listings are digest candidates.",
    },
    {
        "command_id": "v14_publishable_criteria_validation",
        "category": "publishing_quality",
        "command": "python scripts/validate_publishable_criteria.py",
        "purpose": "Validate minimum publishable criteria against known historical golden events.",
        "primary_outputs": "results/v14_publishable_criteria_validation.csv; results/v14_publishable_criteria_validation_summary.csv",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Golden sample contains expected publishable and non-publishable events; script fails if criteria rejects expected publishable events or admits expected rejects.",
    },
    {
        "command_id": "v14_adversarial_golden_validation",
        "category": "publishing_quality",
        "command": "python scripts/generate_adversarial_golden_samples.py",
        "purpose": "Generate adversarial publishable/non-publishable samples and validate criteria against boundary cases.",
        "primary_outputs": "data/v14_adversarial_golden_events.csv; results/v14_adversarial_golden_validation.csv; results/v14_adversarial_golden_validation_summary.csv",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Expected to expose some false positives/false negatives; a perfect score is suspicious rather than desirable.",
    },
    {
        "command_id": "v14_etf_daily_digest_with_baseline",
        "category": "daily_digest",
        "command": "python scripts/build_etf_daily_digest_with_baseline.py",
        "purpose": "Build ETF daily digest with rolling 90d percentile, same-period comparison, top ETF share, and calendar-effect threshold adjustment.",
        "primary_outputs": "results/v14_etf_daily_digest_with_context.md; results/v14_etf_daily_digest_with_context_summary.csv",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Uses already exported Farside data. Belongs in morning/evening digest, not high-frequency intraday alerts.",
    },
    {
        "command_id": "v14_hyperliquid_snapshot_card_v2",
        "category": "daily_digest",
        "command": "python scripts/aggregate_hyperliquid_snapshot_with_baseline.py",
        "purpose": "Aggregate Hyperliquid monitored positions with available baseline, market share, HYPE/non-HYPE long-short split, and liquidation-risk wording.",
        "primary_outputs": "results/v14_hyperliquid_snapshot_card_v2.md; results/v14_hyperliquid_snapshot_v2_summary.csv",
        "safe_default": "conditional",
        "requires_network": "yes",
        "requires_secret": "no",
        "notes": "Uses Hyperliquid public API for total open interest. If 24h baseline is missing, the card must explicitly say so.",
    },
    {
        "command_id": "v14_project_os_warning_review",
        "category": "project_os",
        "command": "python scripts/review_project_os_warnings.py",
        "purpose": "Classify non-blocking Project OS review items so they do not hide real launch blockers.",
        "primary_outputs": "results/v14_project_os_warning_review.csv; results/v14_project_os_warning_review.md",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Review report only; does not suppress validation warnings.",
    },
    {
        "command_id": "v14_false_positive_monitor",
        "category": "publishing_quality",
        "command": "python scripts/build_false_positive_monitor.py",
        "purpose": "Build offline false-positive and false-negative monitoring from adversarial validation without relying on user feedback.",
        "primary_outputs": "results/v14_false_positive_monitor.csv; results/v14_false_positive_monitor_summary.csv; results/v14_false_positive_monitor.md",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Uses historical/adversarial validation only. Does not require TG user feedback or manual review.",
    },
    {
        "command_id": "v14_false_negative_case_review",
        "category": "publishing_quality",
        "command": "python scripts/review_false_negative_cases.py",
        "purpose": "Review false-negative cases and identify required cross-validation evidence before loosening source gates.",
        "primary_outputs": "results/v14_false_negative_case_review.csv; results/v14_false_negative_case_review_summary.csv; results/v14_false_negative_case_review.md",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Does not auto-loosen source_basis rules; produces evidence requirements for later rule changes.",
    },
    {
        "command_id": "v14_hyperliquid_baseline_readiness",
        "category": "daily_digest",
        "command": "python scripts/validate_hyperliquid_baseline_readiness.py",
        "purpose": "Validate whether Hyperliquid snapshot baseline is mature enough to remove Beta wording from daily digests.",
        "primary_outputs": "results/v14_hyperliquid_baseline_readiness.csv; results/v14_hyperliquid_baseline_readiness.md",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Uses existing Hyperliquid summary; does not wait or fetch live data.",
    },
    {
        "command_id": "v14_weekly_fp_analysis",
        "category": "publishing_quality",
        "command": "python scripts/build_weekly_fp_analysis.py",
        "purpose": "Build weekly offline FP/FN analysis from validation monitors, including reason distribution and rule-improvement next actions.",
        "primary_outputs": "results/v14_weekly_fp_analysis.md; results/v14_weekly_fp_analysis_summary.csv",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Historical/offline validation only; no user feedback dependency.",
    },
    {
        "command_id": "v14_market_state_snapshot",
        "category": "daily_digest",
        "command": "python scripts/build_market_state_snapshot.py",
        "purpose": "Fetch public Binance USD-M price, volume, open-interest, funding, and crowding context for the first screen of TG digests.",
        "primary_outputs": "results/v14_market_state_snapshot.csv; results/v14_market_state_snapshot_summary.csv; results/v14_market_state_snapshot.md",
        "safe_default": "yes",
        "requires_network": "yes",
        "requires_secret": "no",
        "notes": "Observation-only market-structure context. Does not generate trade directions or orders.",
    },
    {
        "command_id": "v14_focus_assets",
        "category": "daily_digest",
        "command": "python scripts/market/select_focus_assets.py",
        "purpose": "Select BTC/ETH-first focus assets and prevent small-cap assets from polluting TG digest first screen unless extreme thresholds are met.",
        "primary_outputs": "results/v14_focus_assets.csv; results/v14_focus_assets_summary.csv",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Uses config/asset_tiers.yaml and market-state snapshot rows.",
    },
    {
        "command_id": "v14_price_oi_quadrant",
        "category": "daily_digest",
        "command": "python scripts/market/classify_price_oi_quadrant.py",
        "purpose": "Classify price/open-interest combinations into plain-Chinese market-structure explanations.",
        "primary_outputs": "results/v14_price_oi_quadrant.csv; results/v14_price_oi_quadrant_summary.csv",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Observation-only explanation layer; does not output trading instructions.",
    },
    {
        "command_id": "v14_etf_plain_summary",
        "category": "daily_digest",
        "command": "python scripts/reporting/generate_etf_summary.py",
        "purpose": "Convert ETF daily flow percentile context into a short Chinese first-screen digest block.",
        "primary_outputs": "results/v14_etf_plain_summary.md; results/v14_etf_plain_summary.csv; results/v14_etf_concentration_interpretation.txt",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Uses existing BTC ETF context summary and optional data/eth_etf_flows_farside.csv. ETH missing data is not faked.",
    },
    {
        "command_id": "v14_eth_etf_fetch",
        "category": "daily_digest",
        "command": "python scripts/build_etf_daily_digest.py --asset ETH --url https://farside.co.uk/eth/ --output data/eth_etf_flows_farside.csv --digest-output results/v14_eth_etf_daily_digest.md --summary results/v14_eth_etf_daily_digest_summary.csv",
        "purpose": "Attempt to fetch public Farside ETH ETF flow table into local CSV for ETF first-screen summary.",
        "primary_outputs": "data/eth_etf_flows_farside.csv; results/v14_eth_etf_daily_digest.md; results/v14_eth_etf_daily_digest_summary.csv",
        "safe_default": "yes",
        "requires_network": "yes",
        "requires_secret": "no",
        "notes": "Currently may return warning/no_rows_parsed if Farside Cloudflare blocks local scraping. Do not fabricate ETH ETF data.",
    },
    {
        "command_id": "v14_market_state_first_screen",
        "category": "daily_digest",
        "command": "python scripts/reporting/generate_market_state_summary.py",
        "purpose": "Generate a concise first-screen market-state block for TG morning/noon/evening digest.",
        "primary_outputs": "results/v14_market_state_first_screen.md; results/v14_market_state_first_screen_summary.csv",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Runs focus asset, quadrant, and ETF summary dependencies before rendering.",
    },
    {
        "command_id": "v14_market_alert_headline",
        "category": "daily_digest",
        "command": "python scripts/reporting/generate_alert_headline.py",
        "purpose": "Generate one plain-Chinese abnormality headline for the top of TG market-state digest.",
        "primary_outputs": "results/v14_market_alert_headline.txt; results/v14_market_alert_headline_summary.csv",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Triggers on major BTC/ETH moves, ETF extremes, funding extremes, and high-priority event density.",
    },
    {
        "command_id": "v14_derivatives_history_percentiles",
        "category": "daily_digest",
        "command": "python scripts/market/build_derivatives_history_percentiles.py",
        "purpose": "Fetch public Binance USD-M funding-rate and open-interest history and compute historical percentiles for TG market-state context.",
        "primary_outputs": "data/funding_rate/funding_rate_percentiles.csv; data/oi/oi_percentiles.csv; results/v14_derivatives_history_percentiles_summary.csv; results/v14_derivatives_history_percentiles.md",
        "safe_default": "yes",
        "requires_network": "yes",
        "requires_secret": "no",
        "notes": "Uses 90d funding history and 4h OI history to avoid waiting for local accumulation. Observation-only context.",
    },
    {
        "command_id": "v15_percentile_alerts",
        "category": "daily_digest",
        "command": "python scripts/market/generate_percentile_alerts.py",
        "purpose": "Convert derivative historical percentiles into layered TG placement buckets: first-screen alerts, today-watch candidates, radar triggers, and digest-only context.",
        "primary_outputs": "results/v15_percentile_alerts.json; results/v15_percentile_alerts.csv; results/v15_percentile_alerts.md; results/v15_percentile_alerts_summary.csv",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Uses existing market-state and derivative-percentile files. Observation-only wording; no trading instructions.",
    },
    {
        "command_id": "v15_hyperliquid_market_meta",
        "category": "first_hand_intel",
        "command": "python scripts/hyperliquid/fetch_market_meta.py && python scripts/hyperliquid/generate_market_meta_card.py",
        "purpose": "Fetch Hyperliquid official public perp market metadata and render a concise market-structure card.",
        "primary_outputs": "data/hyperliquid/market_meta_snapshot.csv; data/hyperliquid/market_meta_history.csv; results/v15_hyperliquid_market_meta_card.md; results/v15_hyperliquid_market_meta_summary.csv",
        "safe_default": "yes",
        "requires_network": "yes",
        "requires_secret": "no",
        "notes": "Uses official public info API metaAndAssetCtxs. Does not use third-party liquidation heatmap estimates.",
    },
    {
        "command_id": "v15_hyperliquid_liquidation_wall",
        "category": "first_hand_intel",
        "command": "python scripts/hyperliquid/generate_liquidation_wall.py",
        "purpose": "Group monitored Hyperliquid large positions into nearest liquidation-wall context for radar or digest routing.",
        "primary_outputs": "results/v15_hyperliquid_liquidation_wall.md; results/v15_hyperliquid_liquidation_wall.csv; results/v15_hyperliquid_liquidation_wall_summary.csv",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Uses only local monitored position state. Distance under 5% is radar; under 10% is digest; otherwise hidden.",
    },
    {
        "command_id": "v14_prioritized_events",
        "category": "daily_digest",
        "command": "python scripts/events/prioritize_events.py",
        "purpose": "Audit which TG digest events become top-watch versus other-dynamic items, with explicit scoring reasons.",
        "primary_outputs": "results/v14_prioritized_events.csv; results/v14_today_focus_events.csv; results/v14_other_events.csv; results/v14_prioritized_events.md; results/v14_prioritized_events_summary.csv",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Static large positions are downweighted; top-watch is capped at three items.",
    },
    {
        "command_id": "v14_e2e_publish_preview",
        "category": "publishing_quality",
        "command": "python scripts/test_end_to_end_publish.py",
        "purpose": "Build local end-to-end publish preview from ETF and first-hand watcher candidates without sending Telegram.",
        "primary_outputs": "results/v14_e2e_publish_preview.md; results/v14_e2e_publish_preview_summary.csv",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Local preview only. Does not send messages.",
    },
    {
        "command_id": "v14_hyperliquid_snapshot_card",
        "category": "daily_digest",
        "command": "python scripts/aggregate_hyperliquid_snapshot.py",
        "purpose": "Aggregate Hyperliquid static position snapshots into morning/evening background card.",
        "primary_outputs": "results/v14_hyperliquid_snapshot_card.md; results/v14_hyperliquid_snapshot_summary.csv",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Static position snapshots are background context only. Real-time alerting requires state changes.",
    },
    {
        "command_id": "signal_decay_curve_v11",
        "category": "source_quality",
        "command": "python scripts/build_signal_decay_curve.py --outcomes data/tg_alert_outcomes.csv --historical-backfill results/v08_historical_replay_broad_200_price_backfill.csv --historical-quality results/v08_historical_replay_broad_200_quality_report.csv --output results/signal_decay_curve.csv --summary results/signal_decay_curve_summary.csv --markdown-output results/signal_decay_curve.md",
        "purpose": "Build horizon-level signal decay curves for event type/source subtype groups.",
        "primary_outputs": "results/signal_decay_curve.md; results/signal_decay_curve.csv; results/signal_decay_curve_summary.csv",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Used to avoid overstating short-lived or immature signals.",
    },
    {
        "command_id": "false_positive_analysis_v11",
        "category": "source_quality",
        "command": "python scripts/build_false_positive_analysis.py --outcomes data/tg_alert_outcomes.csv --decision-log data/tg_radar_decision_log.csv --output results/false_positive_analysis.csv --summary results/false_positive_analysis_summary.csv --markdown-output results/false_positive_analysis.md",
        "purpose": "Analyze likely false-positive/noisy TG alert groups from outcome rows and radar decision logs.",
        "primary_outputs": "results/false_positive_analysis.md; results/false_positive_analysis.csv; results/false_positive_analysis_summary.csv",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Uses statistical/passive feedback only. Does not rely on user reactions and does not produce trade instructions.",
    },
    {
        "command_id": "signal_policy_v11",
        "category": "source_quality",
        "command": "python scripts/build_v11_signal_policy.py --event-matrix results/event_type_performance_matrix.csv --non-benchmark-event-matrix results/event_type_performance_matrix_non_benchmark_alt.csv --source-effectiveness results/source_effectiveness_report.csv --false-positive results/false_positive_analysis.csv --output data/tg_signal_policy_v11.csv --summary results/v11_signal_policy_summary.csv --report results/v11_signal_policy_report.md",
        "purpose": "Build machine-readable TG routing policy from historical matrix, source effectiveness, and passive false-positive analysis.",
        "primary_outputs": "data/tg_signal_policy_v11.csv; results/v11_signal_policy_report.md; results/v11_signal_policy_summary.csv",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Controls priority and cooldown only. It does not create trade direction or buy/sell advice.",
    },
    {
        "command_id": "source_adapter_validation_v11",
        "category": "source_quality",
        "command": "python scripts/validate_source_adapter_outputs.py --input data/watcher_events_raw.csv --registry data/source_registry.csv --output results/source_adapter_validation_report.csv --summary results/source_adapter_validation_summary.csv --markdown-output results/source_adapter_validation_report.md",
        "purpose": "Validate normalized watcher/news/calendar source outputs against the v11 adapter schema and registry.",
        "primary_outputs": "results/source_adapter_validation_report.md; results/source_adapter_validation_report.csv; results/source_adapter_validation_summary.csv",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Adapter QA only. Prevents unregistered or malformed sources from quietly entering downstream reports.",
    },
    {
        "command_id": "shadow_source_evaluation_v11",
        "category": "source_quality",
        "command": "python scripts/run_shadow_source_evaluation.py --registry data/source_registry.csv --watcher-events data/watcher_events_raw.csv --shadow-output data/shadow_events_raw.csv --summary results/shadow_source_evaluation_summary.csv --report results/shadow_source_evaluation_report.md",
        "purpose": "Extract shadow-mode source events and summarize whether they are ready for live routing.",
        "primary_outputs": "data/shadow_events_raw.csv; results/shadow_source_evaluation_report.md; results/shadow_source_evaluation_summary.csv",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Keeps unproven sources in shadow until enough evidence exists.",
    },
    {
        "command_id": "tg_evidence_snippets_v11",
        "category": "publishing_quality",
        "command": "python scripts/render_tg_evidence_snippet.py --alerts data/tg_alert_ledger.csv --event-matrix results/event_type_performance_matrix.csv --source-effectiveness results/source_effectiveness_report.csv --output data/tg_evidence_snippets.csv --markdown-output results/tg_evidence_snippets.md",
        "purpose": "Render evidence-based snippets for TG cards and digests using source effectiveness and event performance data.",
        "primary_outputs": "data/tg_evidence_snippets.csv; results/tg_evidence_snippets.md",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Replaces black-box wording with sample-count and quality caveats.",
    },
    {
        "command_id": "llm_usage_report_v11",
        "category": "cost_control",
        "command": "python scripts/build_llm_usage_report.py --input data/llm_usage_ledger.csv --output results/llm_usage_report.csv --summary results/llm_usage_summary.csv --markdown-output results/llm_usage_report.md",
        "purpose": "Summarize Claude/OpenRouter call count, token usage, estimated spend, and failure rate.",
        "primary_outputs": "results/llm_usage_report.md; results/llm_usage_report.csv; results/llm_usage_summary.csv",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "No secrets are logged. Historical calls before the ledger patch are not backfilled.",
    },
    {
        "command_id": "readiness_report_v11",
        "category": "source_quality",
        "command": "python scripts/build_v11_readiness_report.py --output results/v11_readiness_report.md --summary results/v11_readiness_summary.csv",
        "purpose": "Build one readiness report across source registry, adapter validation, source effectiveness, event matrix, signal decay, shadow mode, evidence snippets, digest preview, and LLM cost.",
        "primary_outputs": "results/v11_readiness_report.md; results/v11_readiness_summary.csv",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "This is the current v11 progress dashboard and explicitly reports weak evidence instead of overstating conclusions.",
    },
    {
        "command_id": "import_token_unlock_calendar_v081",
        "category": "source_quality",
        "command": "python scripts/import_raw_token_unlocks_to_calendar.py --input data/raw_token_unlocks_template.csv --output data/token_unlock_calendar_imported.csv",
        "purpose": "Normalize a raw token-unlock CSV export into the local token_unlock_calendar schema without overwriting the live calendar.",
        "primary_outputs": "data/token_unlock_calendar_imported.csv; results/v081_token_unlock_import_report.md; results/v081_token_unlock_import_summary.csv",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Default output is a preview file. Use --output data/token_unlock_calendar.csv only after reviewing quality.",
    },
    {
        "command_id": "v06_intake_quality",
        "category": "event_intake",
        "command": "python scripts/run_v06_event_intake_quality.py --input data/event_candidates_real_500_older_review_suggested.csv",
        "purpose": "Run v0.6 entity/taxonomy/dedup/relevance pipeline on older500 candidates.",
        "primary_outputs": "data/event_candidates_v06_enriched.csv; data/event_candidates_v06_relevance_scored.csv; results/v06_relevance_filter_summary.csv",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Local CSV only.",
    },
    {
        "command_id": "time_audit",
        "category": "quality",
        "command": "python scripts/audit_event_time_provenance.py --candidates data/event_candidates_real_500_older_review.csv --backfill results/v043_older_mature50_event_price_backfill.csv --output results/v043_time_provenance_report.csv --summary results/v043_time_provenance_summary.csv",
        "purpose": "Audit event time provenance and price kline lag.",
        "primary_outputs": "results/v043_time_provenance_report.csv; results/v043_time_provenance_summary.csv",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Checks China-time/UTC consistency.",
    },
    {
        "command_id": "v043_relevance_audit",
        "category": "quality",
        "command": "python scripts/audit_v043_selection_against_v06.py",
        "purpose": "Audit the historical v043 selected backtest sample against current v0.6 relevance decisions.",
        "primary_outputs": "results/v043_selection_vs_v06_relevance_audit.md; results/v043_selection_vs_v06_discard_breakdown.csv; results/v043_selection_vs_v06_event_type_impact.csv",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Keeps v043 labeled as a historical baseline when current v0.6 would discard selected rows.",
    },
    {
        "command_id": "price_source_validation",
        "category": "quality",
        "command": "python scripts/validate_price_sources.py --sample-size 30 --output results/price_source_validation_report.csv --recent-output results/recent_price_point_sample.csv",
        "purpose": "Sample Binance price source validation and produce a recent price point for manual checking.",
        "primary_outputs": "results/price_source_validation_report.csv; results/recent_price_point_sample.csv",
        "safe_default": "conditional",
        "requires_network": "yes",
        "requires_secret": "no",
        "notes": "Uses public market data only.",
    },
    {
        "command_id": "symbol_map_validation",
        "category": "quality",
        "command": "python scripts/validate_symbol_map.py",
        "purpose": "Validate data/symbol_map.csv symbols against public Binance spot and USD-M futures exchangeInfo.",
        "primary_outputs": "results/symbol_map_market_validation.md; results/symbol_map_market_validation_summary.csv",
        "safe_default": "conditional",
        "requires_network": "yes",
        "requires_secret": "no",
        "notes": "Public market metadata only; not part of the default quality gate because it depends on network availability.",
    },
    {
        "command_id": "v05_research_validation",
        "category": "backtest",
        "command": "python scripts/run_v05_research_validation.py",
        "purpose": "Run statistical validation on event returns.",
        "primary_outputs": "results/v05_event_return_statistical_validation.md",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Research validation only, not trading advice.",
    },
    {
        "command_id": "v06_clean_low_risk_preview_backtest",
        "category": "backtest",
        "command": "python scripts/run_v06_clean_low_risk_preview_backtest.py --limit 50",
        "purpose": "Run a non-destructive sanity-check backtest on the current v0.6 clean low-risk preview subset.",
        "primary_outputs": "results/v06_clean_low_risk_preview_event_price_backfill.csv; results/v06_clean_low_risk_preview_backtest_findings.md",
        "safe_default": "conditional",
        "requires_network": "yes",
        "requires_secret": "no",
        "notes": "Preview only; too small for statistical conclusions and does not replace v043 historical outputs.",
    },
    {
        "command_id": "tg_draft_private_pilot",
        "category": "publishing_draft",
        "command": "python scripts/generate_tg_drafts.py --input data/event_candidates_v06_clean_low_risk_preview.csv --output data/tg_drafts_v06_private_pilot.csv --markdown-output results/tg_drafts_v06_private_pilot.md --limit 20",
        "purpose": "Generate local Telegram-style private pilot drafts without calling Telegram or sending messages.",
        "primary_outputs": "data/tg_drafts_v06_private_pilot.csv; results/tg_drafts_v06_private_pilot.md",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Draft-only queue; every row remains pending_review and auto_send_enabled=false.",
    },
    {
        "command_id": "tg_draft_prefilter",
        "category": "publishing_draft",
        "command": "python scripts/prefilter_tg_draft_candidates.py --input data/event_candidates_v06_clean_low_risk_preview.csv --output data/event_candidates_v06_tg_prefilter_pass.csv --rejects-output data/event_candidates_v06_tg_prefilter_rejects.csv --summary results/tg_draft_prefilter_summary.csv",
        "purpose": "Apply local pre-Claude filters for duplicates, weak generic content, weak marketing/adoption stories, and incomplete titles.",
        "primary_outputs": "data/event_candidates_v06_tg_prefilter_pass.csv; data/event_candidates_v06_tg_prefilter_rejects.csv; results/tg_draft_prefilter_summary.csv",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Reduces Claude calls by filtering obvious rejects locally.",
    },
    {
        "command_id": "tg_draft_feedback_summary",
        "category": "publishing_draft",
        "command": "python scripts/summarize_tg_draft_feedback.py --input data/tg_drafts_v06_private_pilot.csv --summary results/tg_draft_feedback_summary.csv --markdown-output results/tg_draft_feedback_summary.md",
        "purpose": "Summarize local TG draft private-pilot feedback after reviewer fields are filled.",
        "primary_outputs": "results/tg_draft_feedback_summary.csv; results/tg_draft_feedback_summary.md",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Local review metrics only; does not approve auto-send.",
    },
    {
        "command_id": "tg_draft_ai_review",
        "category": "publishing_draft",
        "command": "python scripts/ai_review_tg_drafts.py --input data/tg_drafts_v06_private_pilot.csv --output data/tg_drafts_v06_private_pilot_ai_reviewed.csv --summary results/tg_draft_ai_review_summary.csv --limit 20 --apply",
        "purpose": "Use Claude/OpenRouter to review local TG drafts and fill reviewer fields.",
        "primary_outputs": "data/tg_drafts_v06_private_pilot_ai_reviewed.csv; results/tg_draft_ai_review_summary.csv",
        "safe_default": "conditional",
        "requires_network": "yes",
        "requires_secret": "yes",
        "notes": "Requires OPENROUTER_API_KEY only in the current terminal environment. Review suggestions only; no Telegram send.",
    },
    {
        "command_id": "tg_approved_pool",
        "category": "publishing_draft",
        "command": "python scripts/build_approved_tg_draft_pool.py --input data/tg_drafts_v06_private_pilot.csv --output data/tg_drafts_v06_approved_pool.csv --summary results/tg_draft_approved_pool_summary.csv --markdown-output results/tg_draft_approved_pool.md",
        "purpose": "Build approved-only local TG draft pool from AI-reviewed draft queue.",
        "primary_outputs": "data/tg_drafts_v06_approved_pool.csv; results/tg_draft_approved_pool.md",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Does not send messages; approved pool is still local.",
    },
    {
        "command_id": "tg_draft_review_packet",
        "category": "publishing_draft",
        "command": "python scripts/prepare_tg_draft_review_packet.py --input data/tg_drafts_v06_private_pilot.csv --output data/tg_draft_review_packet.csv --markdown-output results/tg_draft_review_packet.md --limit 20 --only-pending",
        "purpose": "Prepare a compact packet for reviewing local TG drafts without editing the wide draft CSV directly.",
        "primary_outputs": "data/tg_draft_review_packet.csv; results/tg_draft_review_packet.md",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Review helper only; does not send or approve messages.",
    },
    {
        "command_id": "tg_draft_apply_review_packet",
        "category": "publishing_draft",
        "command": "python scripts/apply_tg_draft_review_packet.py --drafts data/tg_drafts_v06_private_pilot.csv --packet data/tg_draft_review_packet.csv --output data/tg_drafts_v06_private_pilot.csv",
        "purpose": "Apply compact review packet fields back to the main local TG draft queue.",
        "primary_outputs": "data/tg_drafts_v06_private_pilot.csv; results/tg_draft_review_packet_apply_summary.csv",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Local CSV merge only; does not send or approve externally.",
    },
    {
        "command_id": "tg_draft_validation",
        "category": "publishing_draft",
        "command": "python scripts/validate_tg_drafts.py --input data/tg_drafts_v06_private_pilot.csv --output results/tg_draft_validation_report.csv --summary results/tg_draft_validation_summary.csv --markdown-output results/tg_draft_validation_report.md",
        "purpose": "Validate local TG draft safety: no auto-send, required fields present, no recommendation language.",
        "primary_outputs": "results/tg_draft_validation_report.csv; results/tg_draft_validation_summary.csv",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Hard safety check for draft-only pilot.",
    },
    {
        "command_id": "other_review_reason_split",
        "category": "event_intake",
        "command": "python scripts/classify_other_review_reasons.py --input data/event_candidates_v06_other_review_queue.csv --output data/event_candidates_v06_other_review_classified.csv --summary results/v06_other_review_reason_summary.csv --markdown-output results/v06_other_review_reason_summary.md",
        "purpose": "Split the broad other_review bucket into explicit rule-based review/reject reasons without mutating the source queue.",
        "primary_outputs": "data/event_candidates_v06_other_review_classified.csv; results/v06_other_review_reason_summary.csv",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Supports taxonomy cleanup and discard audit; does not publish or backtest rows.",
    },
    {
        "command_id": "backtest_readiness",
        "category": "backtest",
        "command": "python scripts/build_backtest_readiness_report.py",
        "purpose": "Summarize whether existing backtest outputs are safe to use as statistical conclusions.",
        "primary_outputs": "results/backtest_readiness_report.md; results/backtest_readiness_summary.csv",
        "safe_default": "yes",
        "requires_network": "no",
        "requires_secret": "no",
        "notes": "Conclusion-safety report only; does not run prices or alter samples.",
    },
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build a concise command registry for local Project OS operations.")
    parser.add_argument("--csv-output", default=str(ROOT / "results" / "command_registry.csv"))
    parser.add_argument("--summary", default=str(ROOT / "results" / "command_registry_summary.csv"))
    parser.add_argument("--md-output", default=str(ROOT / "docs" / "COMMAND_REGISTRY.md"))
    return parser.parse_args()


def normalize_path(value: str) -> Path:
    path = Path(value)
    if not path.is_absolute():
        path = ROOT / path
    return path


def referenced_script_exists(command: str) -> bool:
    command_parts = [part.strip() for part in command.split(";") if part.strip()]
    for command_part in command_parts:
        parts = command_part.split()
        for idx, part in enumerate(parts):
            if part == "python" and idx + 1 < len(parts):
                candidate = ROOT / parts[idx + 1]
                if not candidate.exists():
                    return False
                break
    return True


def render_markdown(rows: list[dict]) -> str:
    lines = [
        "# Command Registry",
        "",
        f"Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC+8')}",
        "",
        "This is the short operational command list. It does not replace the detailed Runbook.",
        "",
        "Rules:",
        "",
        "- Prefer `python scripts/run_v06_quality_gate.py` for a full local refresh.",
        "- Do not run commands requiring secrets unless the secret is set only in the current terminal environment.",
        "- Commands here do not permit Notion, trading, web app work, auto-send, or trading advice.",
        "",
        "| id | category | command | network | secret | script_exists |",
        "|---|---|---|---|---|---|",
    ]
    for row in rows:
        command = str(row["command"]).replace("|", "\\|")
        lines.append(
            f"| `{row['command_id']}` | {row['category']} | `{command}` | {row['requires_network']} | {row['requires_secret']} | {row['script_exists']} |"
        )
    lines.extend(
        [
            "",
            "## Details",
            "",
        ]
    )
    for row in rows:
        lines.extend(
            [
                f"### {row['command_id']}",
                "",
                f"Purpose: {row['purpose']}",
                "",
                "```powershell",
                row["command"],
                "```",
                "",
                f"Outputs: `{row['primary_outputs']}`",
                "",
                f"Notes: {row['notes']}",
                "",
            ]
        )
    return "\n".join(lines)


def main() -> int:
    args = parse_args()
    rows = []
    for row in COMMANDS:
        item = dict(row)
        item["script_exists"] = "yes" if referenced_script_exists(item["command"]) else "no"
        rows.append(item)

    csv_output = normalize_path(args.csv_output)
    summary_output = normalize_path(args.summary)
    md_output = normalize_path(args.md_output)
    csv_output.parent.mkdir(parents=True, exist_ok=True)
    summary_output.parent.mkdir(parents=True, exist_ok=True)
    md_output.parent.mkdir(parents=True, exist_ok=True)

    df = pd.DataFrame(rows)
    missing_scripts = int(df["script_exists"].ne("yes").sum())
    secret_commands = int(df["requires_secret"].eq("yes").sum())
    network_commands = int(df["requires_network"].eq("yes").sum())
    df.to_csv(csv_output, index=False)
    pd.DataFrame(
        [
            {
                "command_count": len(df),
                "missing_script_count": missing_scripts,
                "requires_secret_count": secret_commands,
                "requires_network_count": network_commands,
                "status": "pass" if missing_scripts == 0 else "fail",
            }
        ]
    ).to_csv(summary_output, index=False)
    md_output.write_text(render_markdown(rows), encoding="utf-8")
    print(f"wrote command registry to {csv_output}")
    print(f"wrote command registry summary to {summary_output}")
    print(f"wrote command registry markdown to {md_output}")
    return 0 if missing_scripts == 0 else 2


if __name__ == "__main__":
    raise SystemExit(main())
